apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-gradle-ci
data:
  application.properties: |-
    spring.kafka.bootstrap-servers=35.209.57.177:9092
    spring.security.oauth2.resourceserver.jwt.issuer-uri=http://35.209.57.177:8080/auth/realms/master
    spring.redis.host=35.206.91.130
    spring.redis.port=6379
    spring.zipkin.base-url=http://10.73.1.18:9411
    spring.security.oauth2.resourceserver.jwt.issuer-uri=http://35.209.57.177:8080/auth/realms/master
